spring:
  datasource:
    url: jdbc:postgresql://bzu4kqvixtif3srumb7i-postgresql.services.clever-cloud.com:50013/bzu4kqvixtif3srumb7i
    username: uey2kn2mgjbojyjk6kkk
    password: bxtNRhrBx3JkBluVtEB02zITecYUL0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true