spring:
  datasource:
    url: jdbc:postgresql://bnnannaz1jncfransaly-postgresql.services.clever-cloud.com:50013/bnnannaz1jncfransaly
    username: urih4g4k0nnkaszjnkas
    password: y6CM7DqEwl0IGWJGjeTa2eSCXrYveF
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true