spring:
  datasource:
    url: jdbc:postgresql://bpkjshsp1bzu4lqvjmsh-postgresql.services.clever-cloud.com:50013/bpkjshsp1bzu4lqvjmsh
    username: u5qojjknpghkdjudrovi
    password: oGhnXpi57hMTCrYXRerggnpBF6hoUx
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true