spring:
  datasource:
    url: jdbc:postgresql://bipkjmtsvsuygxas5kfr-postgresql.services.clever-cloud.com:50013/bipkjmtsvsuygxas5kfr
    username: u4alg6cg0ddpt6a2bw8l
    password: kaw0ZG12cUC68FydjyAJD7daoxPOYf
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true