spring:
  datasource:
    url: jdbc:postgresql://biw1gmmvictkobr0xom6-postgresql.services.clever-cloud.com:50013/biw1gmmvictkobr0xom6
    username: uy2mi4qqzezpfvtug73i
    password: 3e8MLVb7r2OdFy13ohZEYiiHYSMvXy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true