spring:
  datasource:
    url: jdbc:postgresql://bemu8t1vdhlpzunuuvfq-postgresql.services.clever-cloud.com:50013/bemu8t1vdhlpzunuuvfq
    username: uf9k9sbwpechzhfwmzjd
    password: Xf24KR7t2G88uXBLcVvA8ey0zwVA0B
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true