spring:
  datasource:
    url: jdbc:postgresql://bbfspetrgpdzd12dd5fv-postgresql.services.clever-cloud.com:50013/bbfspetrgpdzd12dd5fv
    username: upngsq0e8v0tic2inbku
    password: JtHkJ5XaEGlO6QzkfQREGCea37B7DP
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true