spring:
  datasource:
    url: jdbc:postgresql://bgj5vhldwtowp0qtuaym-postgresql.services.clever-cloud.com:50013/bgj5vhldwtowp0qtuaym
    username: uczr5fodf8gjxzzs6czs
    password: n4mAuPp3TPVXG6y9FSDvG4fABRDsG2
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true