spring:
  datasource:
    url: jdbc:postgresql://bkzqi2qsyqet939plqhx-postgresql.services.clever-cloud.com:50013/bkzqi2qsyqet939plqhx
    username: upzntmeh2ebawadbys4g
    password: WDwKue3wunojj4bHVBgLzpOwAYwcFo
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true