spring:
  datasource:
    url: jdbc:postgresql://baggtg1axbntgtgxz7sg-postgresql.services.clever-cloud.com:50013/baggtg1axbntgtgxz7sg
    username: ud6wxrperetmo6otkjdw
    password: pZxPk9ifszPjg2vNNKCmS4rzn90oOH
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true