spring:
  datasource:
    url: jdbc:postgresql://b22lxj9wdfxehinluo2a-postgresql.services.clever-cloud.com:50013/b22lxj9wdfxehinluo2a
    username: ubqq6qx38rfsknjal88c
    password: BnVgjQSacXmFSAbAEnW1IbnIMKOg1k
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true