spring:
  datasource:
    url: jdbc:postgresql://bsqnynouszyxksb2sm6g-postgresql.services.clever-cloud.com:50013/bsqnynouszyxksb2sm6g
    username: uqffxbdlsofw6ex1zz9m
    password: yKHIqcKkSX4Erjd0018dYaMTQexEti
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true