spring:
  datasource:
    url: jdbc:postgresql://bbc7j6jynrnotfachtvt-postgresql.services.clever-cloud.com:50013/bbc7j6jynrnotfachtvt
    username: u4zvcpnnw4n1zzhpeu1b
    password: hVtRZtrnlMhc7vCcBBXdkFcY8XfKMy
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true