spring:
  datasource:
    url: jdbc:postgresql://b0pe7guwetye3dnowekk-postgresql.services.clever-cloud.com:50013/b0pe7guwetye3dnowekk
    username: uz7yhuw75r3ec56vaegy
    password: 3ae38vCmu1og2GYZBNTW9oVkuPBaYh
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true