spring:
  datasource:
    url: jdbc:postgresql://b6ft18kytywl3gr6ntr8-postgresql.services.clever-cloud.com:50013/b6ft18kytywl3gr6ntr8
    username: ulizz199xxrsuv5fmozx
    password: QWAMGhqeLFBftM1Ow6vH1dWWobst91
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true