spring:
  datasource:
    url: jdbc:postgresql://bprjpwbnnwrndlxijbiy-postgresql.services.clever-cloud.com:50013/bprjpwbnnwrndlxijbiy
    username: uyui4vgxjksjnfbfrwco
    password: RGpBewx987BEADKJdX7JQI5o6j5GMm
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true