spring:
  datasource:
    url: jdbc:postgresql://bgtx0htqxqdhwtod1dya-postgresql.services.clever-cloud.com:50013/bgtx0htqxqdhwtod1dya
    username: u1uggfi90jxze0ycxl1p
    password: AZFxCtAWFx1Pw9FjAGY6SQ4lZyoaas
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true