spring:
  datasource:
    url: jdbc:postgresql://bilcoxb4slizb6uotips-postgresql.services.clever-cloud.com:50013/bilcoxb4slizb6uotips
    username: u8xqcc7sngslophvhoi9
    password: HH6FuwERBRpMa6LC75oRZVuTtJsGkT
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true