spring:
  datasource:
    url: jdbc:postgresql://byqovc5vjjwlpyfazbm0-postgresql.services.clever-cloud.com:50013/byqovc5vjjwlpyfazbm0
    username: upztwssgta5ywbszmlyv
    password: lG1Iw6yWazKE7DUVd6JiBp8O1VrIH3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true