spring:
  datasource:
    url: jdbc:postgresql://bonewfd78ykv3qztsfux-postgresql.services.clever-cloud.com:50013/bonewfd78ykv3qztsfux
    username: uopeuw2oekueehbg109f
    password: y7d9cFoNP8QHnWJeB8BLdvJzjS8XNZ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true