spring:
  datasource:
    url: jdbc:postgresql://bfkbgfdowqvf5kvgejiq-postgresql.services.clever-cloud.com:50013/bfkbgfdowqvf5kvgejiq
    username: ujoj5npfngcrha1b8eta
    password: syqh9DY0r0WvBrhg1tYvAiV27y67tf
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true