spring:
  datasource:
    url: jdbc:postgresql://brte3ciwbyfsjq7vpo2i-postgresql.services.clever-cloud.com:50013/brte3ciwbyfsjq7vpo2i
    username: ufnfvwwnarlrhnirhzqy
    password: IMhN2Jl2jANl9oVvyz7LYYSPGAtZ61
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true