spring:
  datasource:
    url: jdbc:postgresql://byuxglvmch8x4jhvqkoj-postgresql.services.clever-cloud.com:50013/byuxglvmch8x4jhvqkoj
    username: uyd97vfcomwduzzgmnva
    password: nIgK0Rv9C51XmZ3JUGsnZQVM0Ri0jZ
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true