spring:
  datasource:
    url: jdbc:postgresql://bssqcg1yjgd84eqdevas-postgresql.services.clever-cloud.com:50013/bssqcg1yjgd84eqdevas
    username: upfrptla3cjewtyca72o
    password: IRqGUCDPgMxlLd3OwUdx87fBxM21O0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true