spring:
  datasource:
    url: jdbc:postgresql://bjhfzywtdv2hpss35kqy-postgresql.services.clever-cloud.com:50013/bjhfzywtdv2hpss35kqy
    username: usmgdq1jfaeoqjbkoy06
    password: 6zCjoN6Z5th4i6SDPMDBSvT36WCypH
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true