spring:
  datasource:
    url: jdbc:postgresql://b6iwpjze8fkeesbdxzjj-postgresql.services.clever-cloud.com:50013/b6iwpjze8fkeesbdxzjj
    username: uiztteeyjzjipxldfag7
    password: tqpguimeD8YLZe6krI2ajTyO1zv2yt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true