spring:
  datasource:
    url: jdbc:postgresql://bpeecmydxxyoy3hzv4q5-postgresql.services.clever-cloud.com:50013/bpeecmydxxyoy3hzv4q5
    username: ulwheqn911bqezszxpoz
    password: RL36SRVK474S1YpGKeY7RHAiY5LBJL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true