spring:
  datasource:
    url: jdbc:postgresql://brq6acqlepgwpdo5gqfn-postgresql.services.clever-cloud.com:50013/brq6acqlepgwpdo5gqfn
    username: urlywkgxe6ijhuojqvgs
    password: Y6qlsFjPlME7cZbOVG0rbI0QzlYP4P
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true