spring:
  datasource:
    url: jdbc:postgresql://bnfg0hzpbgzcsfw4vhjr-postgresql.services.clever-cloud.com:50013/bnfg0hzpbgzcsfw4vhjr
    username: uhfuiqadowbkhhkfguie
    password: sDx2ys6zwNcPjUzGR28ELBfvXwSOSV
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true