spring:
  datasource:
    url: jdbc:postgresql://bcxfwhjmg5bcotqfywgm-postgresql.services.clever-cloud.com:50013/bcxfwhjmg5bcotqfywgm
    username: uartipdw30cdjlgmuivo
    password: mvUUrFlUBdYluMqrCffEygLGsYpnWr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true