spring:
  datasource:
    url: jdbc:postgresql://bt3hibawkqpzcvenept3-postgresql.services.clever-cloud.com:50013/bt3hibawkqpzcvenept3
    username: ueovk6ucztxdzqtmo5mz
    password: q9Yze1pL8HAdQbEMo8gPNEs0ESao2i
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true