spring:
  datasource:
    url: jdbc:postgresql://b9myqdndqmguauyywpwa-postgresql.services.clever-cloud.com:50013/b9myqdndqmguauyywpwa
    username: uejqv2uhkseqobynu7ix
    password: vRFCG6IseA8lvp6qyLN4w9H2CLEIOS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true