spring:
  datasource:
    url: jdbc:postgresql://bxxgtg1vne6jj0hlvrui-postgresql.services.clever-cloud.com:50013/bxxgtg1vne6jj0hlvrui
    username: uusfjlgyuykyemtnvgxs
    password: 8wZH6vCZDhtwXKl6B4OqwI9dP0khur
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true