spring:
  datasource:
    url: jdbc:postgresql://bdv3rc1tty1epn5eg2qp-postgresql.services.clever-cloud.com:50013/bdv3rc1tty1epn5eg2qp
    username: u8ilxupjw7042oxqtfyo
    password: N4Mnml2mdsJGPanSMLdfv9Bx000UdH
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true