spring:
  datasource:
    url: jdbc:postgresql://bmbc9wop8hyffpiaxvtt-postgresql.services.clever-cloud.com:50013/bmbc9wop8hyffpiaxvtt
    username: u6rort3tctej3ldr762z
    password: aTf63BLD83cWdIxQ5nuxDStAHL5UyS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true