spring:
  datasource:
    url: jdbc:postgresql://bnt9379mmz6f6is4zdck-postgresql.services.clever-cloud.com:50013/bnt9379mmz6f6is4zdck
    username: uncoco2lcfosdtd6wf2s
    password: UW0WP7rrHgLx0W6xD9QZOILxHIBKwp
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true