spring:
  datasource:
    url: jdbc:postgresql://br5aktgcpwdfhjwfpqtt-postgresql.services.clever-cloud.com:50013/br5aktgcpwdfhjwfpqtt
    username: umaktnjnemxnmlji3qxs
    password: IYbRZdesczt6eQSrWpJGIzzP4mseYr
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true