spring:
  datasource:
    url: jdbc:postgresql://bdlyncljjerkpda9qt44-postgresql.services.clever-cloud.com:50013/bdlyncljjerkpda9qt44
    username: uct3ev1oafzfglavxoxw
    password: ce8d5H8VZv4W4BR2wyndeADVfj5nwS
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true