spring:
  datasource:
    url: jdbc:postgresql://bgqitszmwtnx17nlzoe9-postgresql.services.clever-cloud.com:50013/bgqitszmwtnx17nlzoe9
    username: uex5nj6qhum3onbfuh4l
    password: Ws1zgmR51wRnqFYVjNKlDmidktw1qz
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true