spring:
  datasource:
    url: jdbc:postgresql://bqidvfe0jgri2mianjew-postgresql.services.clever-cloud.com:50013/bqidvfe0jgri2mianjew
    username: uoawr1hpoyzmxy7yot6h
    password: Ww4XKpVgP1jWMX9Px8TFxdBOVdoS9y
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true