spring:
  datasource:
    url: jdbc:postgresql://bedppbry7ewcaykepijt-postgresql.services.clever-cloud.com:50013/bedppbry7ewcaykepijt
    username: u69jzu0qlzpehxxoareg
    password: RmGhQ1v2hTDr8McTwXMvtOuAkMRd7W
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true