spring:
  datasource:
    url: jdbc:postgresql://bmthtg4prtwprnb3pvc5-postgresql.services.clever-cloud.com:50013/bmthtg4prtwprnb3pvc5
    username: uydmoze0slwdhh8trqjh
    password: ckgvYpmCLSMqkaiduMgzzVNjvUcqdt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true