spring:
  datasource:
    url: jdbc:postgresql://bztxn61ahlqx6adlkemb-postgresql.services.clever-cloud.com:50013/bztxn61ahlqx6adlkemb
    username: uh5mwjvoqcfhxj2mxyve
    password: gk0ntNkeJDmh9rhKHUZT7BaCRtBLsk
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true