spring:
  datasource:
    url: jdbc:postgresql://bqsahxtotyn68qwhre71-postgresql.services.clever-cloud.com:50013/bqsahxtotyn68qwhre71
    username: uro60k0dsk0xlue6uwxk
    password: 5IrvxVQfCuOrJkt3TG8NaNvcJ9jvtd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true