spring:
  datasource:
    url: jdbc:postgresql://buhod30dtp58exk3dwo9-postgresql.services.clever-cloud.com:50013/buhod30dtp58exk3dwo9
    username: uducasyme33eiu62cice
    password: HjBNSPgJ8dqazdsbZqCYqQ5ZUxOxvY
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true