spring:
  datasource:
    url: jdbc:postgresql://bfh8io4zze1ffjdsqih9-postgresql.services.clever-cloud.com:50013/bfh8io4zze1ffjdsqih9
    username: utr3qhxtauaryiblq7g1
    password: gUcsKs4WNxWMfJMlh9JvuoeqXNn7R4
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true