spring:
  datasource:
    url: jdbc:postgresql://bbasjixeva1h3zvcsacn-postgresql.services.clever-cloud.com:50013/bbasjixeva1h3zvcsacn
    username: upadgdmvg05be34rzzcp
    password: akeYRBqODMwvgQHZi7kq9groE6iWrI
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true