spring:
  datasource:
    url: jdbc:postgresql://b0tbpx6owpmgfzopl5kj-postgresql.services.clever-cloud.com:50013/b0tbpx6owpmgfzopl5kj
    username: umny7ucx2a5bttxg9ylf
    password: MWZKKjeGSI7D6Tm4Bx4wpxsnA8NMpe
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true