spring:
  datasource:
    url: jdbc:postgresql://bhg8220jcj3rot0krs1y-postgresql.services.clever-cloud.com:50013/bhg8220jcj3rot0krs1y
    username: unn3oetvu7l2nll1jskd
    password: UjT7qkkhxGgI4absHf8EBeO4LvmARW
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true