spring:
  datasource:
    url: jdbc:postgresql://bkwgyuacbfptludbhweu-postgresql.services.clever-cloud.com:50013/bkwgyuacbfptludbhweu
    username: uicej1z2ywsgod4sesq2
    password: 6XLs5ad9Tfv3HxymsVasZgu1aIQb3X
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true