spring:
  datasource:
    url: jdbc:postgresql://b8j7evzdkkxbnwxjs0db-postgresql.services.clever-cloud.com:50013/b8j7evzdkkxbnwxjs0db
    username: ukmaykzhhdvaq5gxyelg
    password: guNBPSOzqFvVqyQi4OXi5os4YgAYwU
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true