spring:
  datasource:
    url: jdbc:postgresql://bambrsbkwxvxoi99s3bf-postgresql.services.clever-cloud.com:50013/bambrsbkwxvxoi99s3bf
    username: usc0c6gm7wjaowdlv5ea
    password: 8FoY43hl9gXtcSP8xGZisIf25BltX3
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true